### ISSUE TITLE
Can't connect to a private channel "no Authorizer has been set"

### ISSUE THREAD

**Issue by emrade** [heywhy/flutter-pusher-client#12]
When I try to connect to a private channel I get the error "subscribe error: Cannot subscribe to a private or presence channel because no Authorizer has been set. Call PusherOptions.setAuthorizer() before connecting to Pusher".

Can you help me?

**Comment by heywhy** [comment]
You are to set the authorization information on the pusher client instance: 

```dart
var options = PusherOptions(cluster: 'eu', auth: PusherAuth('https://app.com/broadcast/auth', headers: {
  'Authorization': "Bearer $token"
}));
FlutterPusher pusher = FlutterPusher('api_key', options, enableLogging: true,);
```

**Comment by emrade** [comment]
It would be great if you could add it to the docs or example. Thanks
