### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by fabianArlex** [heywhy/flutter-pusher-client#5]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_pusher_client' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

**Comment by heywhy** [comment]
I'll suggest you have a look at this comment: https://github.com/heywhy/flutter-pusher-client/issues/1#issuecomment-575370337

Atanda Rasheed
