### ISSUE TITLE
[Help] IOS Support

### ISSUE THREAD

**Issue by heywhy** [heywhy/flutter-pusher-client#6]
Hello guys, sorry for the pending issue regarding the ios support. I'm not conversant with the ios tools which are why the ios support is pending. I'll be glad if anyone can help out with that, you can get the initial ios integration at [ios-support](https://github.com/heywhy/flutter-pusher-client/tree/ios-support). I'll be glad if anyone can pick up this task and help solve this pending issue. You can also refer someone to help. Thank you.

Atanda Rasheed

**Comment by rizalashidiq97** [comment]
does your packaage working properly in swift based apps ?

**Comment by heywhy** [comment]
I’m not conversant with iOS ecosystem, that’s why I created this issue to have someone help with that

**Comment by jgalindosl** [comment]
I submitted a pull request https://github.com/heywhy/flutter-pusher-client/pull/9 to take care of this issue.

**Comment by heywhy** [comment]
I'm sorry the iOS support came in late because I had to learn swift to be able to support iOS since I couldn't find a contributor to build the support. But I'm glad to announce that a new version of [flutter_pusher_client](https://github.com/heywhy/flutter-pusher-client) has been released. So you are advised to upgrade to the latest version and also upgrade your flutter tools.
